name: Test MonetDB versions
on:
  push:
    branches: [ master, monetdbs ]
  pull_request:

  schedule:
    - cron:  '5 0 * * *'

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: python:3.11
    strategy:
      fail-fast: false
      matrix:
        monetdbversion:
          # at some point we'll have to start removing some of these..
          - default
          - Aug2025
          - Aug2024
          - Dec2023
          - Jun2023
          - Sep2022
          - Jan2022
          - Jun2020
    env:
      TSTHOSTNAME: "monetdb"
      TSTDB: "monetdb"
      TSTPASSPHRASE: "monetdb"
      TSTCONTROL: "tcp"
    services:
      monetdb:
        image: "monetdb/dev-builds:${{ matrix.monetdbversion }}"
        env:
          MDB_DAEMON_PASS: monetdb
          MDB_DB_ADMIN_PASS: monetdb
        ports:
          - 50000:50000
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up tests
        run: make setup
      - name: Run tests
        run: make test
