name: Try the MonetDB test suite
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  mtest:
    runs-on: ubuntu-latest
    env:
      SRC_URL: "https://www.monetdb.org/downloads/sources/Dec2025-SP2/MonetDB-11.55.5.tar.xz"
      SRC_SUM: "480c921a45b54c610dee9a17147f0e89ae74c31516b9250e5c8f2371e1bd70c2"
      TESTS_URL: "https://www.monetdb.org/downloads/sources/Dec2025-SP2/MonetDB-tests-11.55.5.tar.xz"
      TESTS_SUM: "43c022698f5fa43e5b92ac3f6d33be6459a38d7af5ada6a95fad2dd80cd96d64"
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:

      - name: Install packages
        run: sudo apt-get -qq update && sudo apt-get -qq install -y tzdata python3 python3-venv curl xz-utils build-essential ninja-build bison cmake gcc pkg-config libbz2-dev liblz4-dev libpcre2-dev libreadline-dev liblzma-dev libssl-dev zlib1g-dev libasan5 libcfitsio-dev libcmocka-dev libcurl4-gnutls-dev libgdal-dev libgeos-dev libnetcdf-dev libproj-dev libxml2-dev python3-dev python3-numpy r-base-dev unixodbc-dev valgrind

      - name: Check out
        uses: actions/checkout@v6

      - name: Which Python do we have today?
        run: python3 --version

      - name: Create venv with pymonetdb
        run: python3 -m venv venv &&  ./venv/bin/pip install setuptools wheel cryptography lz4 && ./venv/bin/pip install .

      - name: Download MonetDB sources
        run: |
          echo "SRC_URL=$SRC_URL"
          echo "TEST_URL=$TEST_URL"
          curl -s "$SRC_URL" -o monetdb.tar.xz
          curl -s "$TESTS_URL" -o monetdb-tests.tar.xz
          ( echo "$SRC_SUM" monetdb.tar.xz; echo "$TESTS_SUM" monetdb-tests.tar.xz ) | sha256sum -c
          mkdir monetdb && cd monetdb && xzcat ../monetdb.tar.xz | tar xf - --strip-components=1 && xzcat ../monetdb-tests.tar.xz | tar xf - --strip-components=1

      - name: Build MonetDB
        run: . ./venv/bin/activate && cmake -GNinja -S monetdb -B BUILD --install-prefix="$PWD/INST" -DCMAKE_INSTALL_MESSAGE=NEVER && echo && cmake --build BUILD --target install

      - name: Test MonetDB
        run: PATH="$PWD/INST/bin:$PATH"; . ./venv/bin/activate && cd monetdb && time Mtest.py -v --parallel="$(nproc)"

      - name: Store mtest output
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: mtest-output
          path: INST/mTests
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 7





