name: Windows Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  runtests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      # Unfortunately msiexec does seem to work on the windows runner.
      # 7zip is able to unpack .msi files but it loses the directory structure.
      # We fix that in the next step.
      - name: Download MonetDB
        run: |
          curl -L https://www.monetdb.org/downloads/Windows/Latest/MonetDB5-SQL-Installer-x86_64-*.msi -o ${{ runner.temp }}\monetdb.msi --no-progress-meter
          dir ${{ runner.temp }}
          7z x ${{ runner.temp }}\monetdb.msi -o${{ runner.temp }}\staging
          dir ${{ runner.temp }}\staging

      # Run a script to restore the directory structure and see if it works (a little)
      - name: Install MonetDB
        run: |
          python tests/install_monetdb_from_msi_dir.py ${{ runner.temp }}\staging ${{ runner.temp }}\MONET
          dir ${{ runner.temp }}\MONET
          dir ${{ runner.temp }}\MONET\bin
          ${{ runner.temp }}\MONET\bin\mserver5.exe --help

      - name: Setup virtual environment
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          python -m pip install -r tests/requirements.txt

      # Script tests/windows_tests.py starts an mserver in the background
      # and runs pytest, excluding the Control tests.
      - name: run the tests
        run: |
          venv\Scripts\Activate.ps1
          mkdir ${{ runner.temp }}\dbfarm
          python tests/windows_tests.py ${{ runner.temp }}\MONET ${{ runner.temp }}\dbfarm demo 50000
          echo ""; echo ""; echo "================ SERVER STDERR: ==================="; echo ""
          type ${{ runner.temp }}\dbfarm\errlog

