name: Windows Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  windows_wheel:
    continue-on-error: true
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install choco packages
        run: choco install python

